name: Update README with GitHub Activity

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GH_TOKEN: $ {{ secrets.GTIHUB_TOKEN }}
        with:
          COMMIT_MSG: "Commited to: "
          MAX_LINES: 5
          COMMIT_NAME: GitHub Activity Readme
          
